crudminsa/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pacientes/', include("main.urls")),
    path('', RedirectView.as_view(url='pacientes/'), name="index")
]

main/urls.py
from django.urls import path
from main import views

app_name = 'main'

urlpatterns = [
	path('', views.ListarPacienteView.as_view(), name='listar-paciente'),
	path('crear/', views.CrearPacienteView.as_view(), name='crear-paciente'),
	path('<int:id>/', views.DetallePacienteView.as_view(), name='detalle-paciente'),
	path('<int:id>/actualizar/', views.ActualizarPacienteView.as_view(), name='actualizar-paciente'),
	path('<int:id>/eliminar/', views.EliminarPacienteView.as_view(), name='eliminar-paciente')
]

main/models.py
from django.db import models
from django.urls import reverse
import datetime

class TipoDocumento(models.Model):
	tipo = models.CharField(max_length=30)

	def __str__(self):
		return "%s" % self.tipo


class Paciente(models.Model):
	tipo_documento = models.ForeignKey(TipoDocumento, on_delete=models.DO_NOTHING)
	documento = models.CharField(max_length=8, null=True)
	nombre = models.CharField(max_length=50)
	apellido_paterno = models.CharField(max_length=50)
	apellido_materno = models.CharField(max_length=50)
	fecha_nacimiento = models.DateField()

	class Meta:
		unique_together = ('tipo_documento', 'documento')

	def get_absolute_url(self):
		return reverse("main:detalle-paciente", kwargs={"id": self.id})
	
	@property
	def nombre_completo(self):
		return "%s %s %s" % (self.nombre, self.apellido_paterno, self.apellido_materno)

	@property
	def edad(self):
		fecha_nacimiento = self.fecha_nacimiento
		fecha_actual = datetime.date.today()
		
		prox_cumpleaños = datetime.date(fecha_actual.year, fecha_nacimiento.month, fecha_nacimiento.day)
		
		numero_años_cont = fecha_actual.year - fecha_nacimiento.year
		numero_dias_cont = fecha_actual.day
		
		if(prox_cumpleaños.month > fecha_actual.month):
			numero_años_cont -=1
			numero_mes_cont = fecha_actual.month + (11 - fecha_nacimiento.month)
		else:
			numero_mes_cont = (fecha_actual.month - prox_cumpleaños.month) - 1

		if(prox_cumpleaños.month == fecha_actual.month):
			numero_mes_cont = 0
			if(prox_cumpleaños.day > fecha_actual.day):
				numero_años_cont +=1
				numero_mes_cont -=1
				numero_dias_cont = prox_cumpleaños.day - fecha_actual.day
			else:
				numero_dias_cont = fecha_actual.day - prox_cumpleaños.day


		return "%s años, %s meses, %s dias" % (numero_años_cont, numero_mes_cont, numero_dias_cont)

main/forms.py
from django import forms
from .models import Paciente, TipoDocumento

class PacienteForm(forms.ModelForm):
	tipo_documento = forms.ModelChoiceField(
		queryset=TipoDocumento.objects.all(),
		label="Tipo de documento",
		widget=forms.Select(
			attrs={
				"class": "form-control"
			}
		),
	)
	documento = forms.CharField(widget=forms.TextInput(
		attrs={"class": "form-control"}
	))
	nombre = forms.CharField(widget=forms.TextInput(
		attrs={"class": "form-control"}
	))
	apellido_paterno = forms.CharField(
		widget=forms.TextInput(
			attrs={"class": "form-control"}
		)
	)
	apellido_materno = forms.CharField(
		widget=forms.TextInput(
			attrs={"class": "form-control"}
		)
	)
	fecha_nacimiento = forms.CharField(widget=forms.TextInput(
		attrs={"class": "form-control", "type": "date"}
	))

	edad = forms.IntegerField(required=False, widget=forms.TextInput(
		attrs={'readonly': 'readonly'}
	))


	class Meta:
		model = Paciente
		fields = [
			'tipo_documento',
			'documento',
			'nombre',
			'apellido_paterno',
			'apellido_materno',
			'fecha_nacimiento',
			'edad'
		]

main/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from main import models, forms
from django.views.generic import (
	CreateView,
	UpdateView,
	ListView,
	DetailView,
	DeleteView
)

class CrearPacienteView(CreateView):
	template_name = "crear_paciente.html"
	form_class = forms.PacienteForm
	queryset = models.Paciente.objects.all()

	def form_valid(self, form):
		return super().form_valid(form)

	def get_success_url(self):
		return reverse("main:listar-paciente")

class DetallePacienteView(DetailView):
	template_name = "detalle_paciente.html"

	def get_object(self):
		id_ = self.kwargs.get("id")
		return get_object_or_404(models.Paciente, id=id_)

class ActualizarPacienteView(UpdateView):
	template_name = "actualizar_paciente.html"
	form_class = forms.PacienteForm

	def form_valid(self, form):
		return super().form_valid(form)

	def get_object(self):
		id_ = self.kwargs.get("id")
		return get_object_or_404(models.Paciente, id=id_)

	def get_success_url(self):
		return reverse("main:listar-paciente")

class EliminarPacienteView(DeleteView):
	def get_object(self):
		id_ = self.kwargs.get("id")
		return get_object_or_404(models.Paciente, id=id_)

	def get_success_url(self):
		return reverse("main:listar-paciente")

class ListarPacienteView(ListView):
	template_name = "listar_paciente.html"
	queryset = models.Paciente.objects.all()

	def get_context_data(self, **kwargs):
		context_ = super(ListarPacienteView, self).get_context_data(**kwargs)
		context_["tipos_documento"] = models.TipoDocumento.objects.all()
		return context_

main/templates/actualizar_paciente.html
{% extends 'base.html' %}

{% block content %}
	<form action = "{% url 'main:actualizar-paciente' id=object.id %}" method="POST">{% csrf_token %}
		<div class="modal-body">
			<div class="form-row">
				<div class="form-group col-md-6">
					<label>Tipo de documento</label>
					{{ form.tipo_documento }}
				</div>
				<div class="form-group col-md-6">
					<label>Número de documento</label>
					{{ form.documento }}
				</div>
			</div>
			<div class="form-row">
				<div class="form-group col-md-6">
					<label>Nombres</label>
					{{ form.nombre }}
				</div>
			</div>
			<div class="form-row">
				<div class="form-group col-md-6">
					<label>Apellido paterno</label>
					{{ form.apellido_paterno }}
				</div>
				<div class="form-group col-md-6">
					<label>Apellido materno</label>
					{{ form.apellido_materno }}
				</div>
			</div>
			<div class="form-row">
				<div class="form-group col-md-6">
					<label>Fecha de nacimiento</label>
					{{ form.fecha_nacimiento }}
				</div>
				<div class="form-group col-md-6">
					<label>Edad</label>
					{{ form.edad }}
				</div>
			</div>
		<div>
		<div class="modal-footer">
        	<button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
        	<input  type="submit" class="btn btn-primary" value="Guardar">
      	</div>
	</form>

{% endblock %}

main/templates/crear_paciente.html
{% extends 'base.html' %}

{% block content %}
	<form action = '{% url "main:crear-paciente" %}' method="POST">{% csrf_token %}
		<div class="modal-body">
			<div class="form-row">
				<div class="form-group col-md-6">
					<label>Tipo de documento</label>
					{{ form.tipo_documento }}
				</div>
				<div class="form-group col-md-6">
					<label>Número de documento</label>
					{{ form.documento }}
				</div>
			</div>
			<div class="form-row">
				<div class="form-group col-md-6">
					<label>Nombres</label>
					{{ form.nombre }}
				</div>
			</div>
			<div class="form-row">
				<div class="form-group col-md-6">
					<label>Apellido paterno</label>
					{{ form.apellido_paterno }}
				</div>
				<div class="form-group col-md-6">
					<label>Apellido materno</label>
					{{ form.apellido_materno }}
				</div>
			</div>
			<div class="form-row">
				<div class="form-group col-md-6">
					<label>Fecha de nacimiento</label>
					{{ form.fecha_nacimiento }}
				</div>
				<div class="form-group col-md-6">
					<label>Edad</label>
					{{ form.edad }}
				</div>
			</div>
		<div>
		<div class="modal-footer">
        	<button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
        	<input  type="submit" class="btn btn-primary" value="Guardar">
      	</div>
	</form>

{% endblock %}

main/templates/detalle_paciente.html
{% extends 'base.html' %}
{% block content %}

{% endblock %}

main/templates/eliminar_paciente.html
{% extends 'base.html' %}
{% block content %}
	<form action = '.' method="POST">
		<input type="submit" name="Eliminar">
	</form>
{% endblock%}

main/templates/listar_paciente.html
{% extends 'base.html' %}
{% block content %}
<div class="mx-auto">
	<div class="row">
		<div class="col-sm-4">
			<label>Tipo Documento</label>
			<select class="form-control" id="input_search_tipo_doc">
				<option class="form-control" value="todos">--Todos--</option>
				{% for tipo in tipos_documento %}
					<option value="{{ tipo.tipo }}">{{ tipo.tipo }}</option>
				{% endfor %}
			</select>
		</div>
		<div class="col-sm-4">
			<label>Número Documento</label>
			<input type="text" class="form-control" id="input_search_document" onkeypress="search_documento(event)">
		</div>
		<div class="col-sm-4" style="padding-top: 35px;">
			<button id="btn_create_patient" type="button" class="btn btn-primary" data-toggle="modal" data-target="#idModalPaciente">
			  Crear Paciente
			</button>
		</div>
	</div>
</div>
<div class="mx-auto">
	<table id="patient-table" class="table table-striped table-bordered">
		<thead>
			<tr>
				<th>Tipo de documento</th>
				<th>Número de documento</th>
				<th>Fecha de nacimiento</th>
				<th>Edad</th>
				<th>Nombre y apellido</th>
				<th></th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			{% for paciente in object_list %}
				<tr>
					<td>{{ paciente.tipo_documento }}</td>
					<td>{{ paciente.documento }}</td>
					<td>{{ paciente.fecha_nacimiento }}</td>
					<td>{{ paciente.edad }}</td>
					<td>{{ paciente.nombre_completo }}</td>
					<td>
						<button id="btn_edit_patient" onclick="editar_paciente('{{ paciente.get_absolute_url }}actualizar/')" type="button" class="btn btn-primary" data-toggle="modal" data-target="#idModalPaciente">
							Editar
						</button>
					</td>
					<td>
						<form action="{% url 'main:eliminar-paciente' id=paciente.id %}" method="POST">{% csrf_token %}
							<button type="submit" class="btn btn-danger">Eliminar</button>
						</form>
					</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>

	<div class="modal fade" id="idModalPaciente" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
	  <div class="modal-dialog modal-dialog-centered" role="document">
	    <div class="modal-content">
	      <div class="modal-header">
	        <h5 class="modal-title" id="exampleModalLongTitle">Crear/Editar Paciente</h5>
	        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
	          <span aria-hidden="true">&times;</span>
	        </button>
	      </div>
	      <div class="add-form">
	      </div>
	    </div>
	  </div>
	</div>
</div>

{% endblock %}
{% block js%}
	<script >
		$("#patient-table").DataTable()
		table = $("#patient-table").DataTable()
		$(".dataTables_filter").hide()
		$(".dataTables_length").hide()
		$("#btn_create_patient").click(function(){
			$.ajax({
				url: "{% url 'main:crear-paciente'%}",
				type: "get",
				dataType: "text",
				success: function(data){
					$("#idModalPaciente .add-form").html(data)
				}	
			})
		})

		function editar_paciente(url){
			$.ajax({
				url: url,
				type: "get",
				dataType:"text",
				success: function(data){
					$("#idModalPaciente .add-form").html(data)
				}
			})
		}

		$("#input_search_tipo_doc").on("change", function(){
			value = $(this).val()
			if(value == "todos"){
				value = ''
			}
			table.columns(0).search(value)
			table.draw()
		})

		function search_documento(event){
			if(event.keyCode == 13){
				value = $("#input_search_document").val()
				table.columns(1).search(value)
				table.draw()
			}
		}
	</script>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/dataTables.bootstrap4.min.css' %}">
	<title>CRUD-MINSA</title>
</head>
<body>
	<div class="container">	
		{% block content %}

		{% endblock %}
	</div>
	<script src="{% static 'js/jquery.min.js' %}"></script>
	<script src="{% static 'js/jquery.dataTables.min.js' %}"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<script src="{% static 'js/dataTables.bootstrap4.min.js'%}"></script>
	
	{% block js %}

	{% endblock%}
</body>
</html>